### ISSUE TITLE
Consider using `bytemuck` instead of manual `as_u8_slice()`

### ISSUE THREAD

**Issue by djeedai** [djeedai/weldr#29]
It would be safer to let `bytemuck` handle those conversions, the maintainers have put a lot of thinking into making sure their implementation is safe.

See what Rust version `bytemuck` supports; they say 1.34 for base without feature, but do we need any feature?

**Comment by ScanMountGoat** [comment]
The spec for gltf wants all buffer data to be little endian, so we might not need any crates for this at all. We can just use `to_le_bytes()` for each float. https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#buffers-and-buffer-views-overview

**Comment by djeedai** [comment]
Good catch, I didn't know that.
